apiVersion: v1
kind: Service
metadata:
  name: spring-app
  namespace: default
  labels:
    app: spring-app
 # annotations:
 # service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
        # externalTrafficPolicy: Local
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: spring-app
  type: LoadBalancer
